### ISSUE TITLE
Is it possible to make rpmvercmp a public function?

### ISSUE THREAD

**Issue by ryysud** [cavaliergopher/rpm#26]
Thank you for rewriting the original C implementation `rpmvercmp` in golang. 
Since this is a very useful function, is it possible to make it a public fucntion?
https://github.com/cavaliergopher/rpm/blob/v1.1.1/version.go#L63

**Comment by ryysud** [comment]
@cavaliercoder Could you consider this?

**Comment by cavaliercoder** [comment]
Hey, yes I'm open to this. There is already the `Compare` public method, but perhaps you means comparison of strings?

**Comment by ryysud** [comment]
@cavaliercoder Yes, I want to execute a comparison of strings.

**Comment by cavaliercoder** [comment]
Added `CompareVersions` in v1.2.0

**Comment by ryysud** [comment]
Thank you for the quick fix 👍 
I am closing this issue.
